//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaGalleryWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actores()
        {
            this.PeliculasActores = new HashSet<PeliculasActores>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string descripcion { get; set; }
        public string vida_personal { get; set; }
        public string filmografia { get; set; }
        public Nullable<int> Idpelicula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeliculasActores> PeliculasActores { get; set; }
    }
}
