//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaGalleryWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Directores()
        {
            this.PeliculasDirectores = new HashSet<PeliculasDirectores>();
        }
    
        public int Id { get; set; }
        public string carrera { get; set; }
        public string descripcion { get; set; }
        public string filmografia { get; set; }
        public string otros_trabajos { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeliculasDirectores> PeliculasDirectores { get; set; }
    }
}
