//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaGalleryWinForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseCinemaGalleryEntities1 : DbContext
    {
        public DatabaseCinemaGalleryEntities1()
            : base("name=DatabaseCinemaGalleryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actores> Actores { get; set; }
        public virtual DbSet<Directores> Directores { get; set; }
        public virtual DbSet<Peliculas> Peliculas { get; set; }
        public virtual DbSet<PeliculasActores> PeliculasActores { get; set; }
        public virtual DbSet<PeliculasDirectores> PeliculasDirectores { get; set; }
    }
}
