//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaGalleryWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeliculasActores
    {
        public int Id { get; set; }
        public Nullable<int> idpelicula { get; set; }
        public Nullable<int> idactor { get; set; }
    
        public virtual Actores Actores { get; set; }
        public virtual Peliculas Peliculas { get; set; }
    }
}
